[font.bold]
family = "Migu 1M"
style = "Bold"

[font.bold_italic]
family = "Migu 1M"
style = "Bold Italic"

[font.italic]
family = "Migu 1M"
style = "Italic"

[font.normal]
family = "Migu 1M"
style = "Regular"

[mouse]
bindings = [
{mouse="Right", action="Paste"},
]

[window]
opacity = 0.85
