- name: Install packages
  ansible.builtin.apt:
    pkg:
      - docker.io
      - docker-compose
  become: yes
- name: Add group
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: [docker]
    append: yes
  become: yes
